import { NextResponse } from "next/server";
import {
  getAdminReportStats,
  listAdminReports,
  storeCategorySnapshots,
  type AdminReportCategory,
} from "@/lib/admin/admin-reports";
import { requireAdminAuth } from "@/lib/admin-server/require-admin-auth";
import { getUserDb } from "@/lib/user-server/get-user-db";
import { eventsCollection } from "@/lib/events/types";

const CATEGORY_LABELS: Record<AdminReportCategory, string> = {
  event: "Event",
  attendance: "Attendance",
  certificate: "Certificate",
  feedback: "Feedback",
  users: "Users",
};

function parseCategory(value: string | null): AdminReportCategory | null {
  const normalized = String(value || "").toLowerCase();
  if (normalized === "event") return "event";
  if (normalized === "attendance") return "attendance";
  if (normalized === "certificate") return "certificate";
  if (normalized === "feedback") return "feedback";
  if (normalized === "users") return "users";
  return null;
}

async function buildUsersCsv(db: Awaited<ReturnType<typeof getUserDb>>) {
  const users = await db
    .collection("users")
    .find({ role: { $nin: ["admin", "super-admin"] } })
    .project({
      fullName: 1,
      email: 1,
      course: 1,
      organizationPart: 1,
      role: 1,
      rfidNumber: 1,
    })
    .sort({ fullName: 1 })
    .limit(5000)
    .toArray();

  const header = "Name,Email,Course,Organization,Role,RFID";
  const lines = users.map((user) => {
    const cols = [
      String(user.fullName || ""),
      String(user.email || ""),
      String(user.course || ""),
      String(user.organizationPart || ""),
      String(user.role || ""),
      String(user.rfidNumber || ""),
    ];
    return cols.map((col) => `"${col.replace(/"/g, '""')}"`).join(",");
  });
  return [header, ...lines].join("\n");
}

async function loadLiveCounts(db: Awaited<ReturnType<typeof getUserDb>>) {
  const [events, usersCount, attendanceCount, feedbackCount, certCount] = await Promise.all([
    eventsCollection(db).find({}).sort({ updatedAt: -1 }).limit(50).toArray(),
    db.collection("users").countDocuments({
      role: { $nin: ["admin", "super-admin"] },
    }),
    db.collection("attendance_records").countDocuments({}),
    db.collection("feedback_entries").countDocuments({}),
    db.collection("certificates").countDocuments({}),
  ]);
  return { events, usersCount, attendanceCount, feedbackCount, certCount };
}

function buildCsv(
  authName: string,
  counts: {
    events: Array<{ title?: string; status?: string; organizerName?: string; organizerEmail?: string; updatedAt?: string }>;
    usersCount: number;
    attendanceCount: number;
    feedbackCount: number;
    certCount: number;
  },
) {
  const date = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const rows = [
    {
      name: "Events Summary",
      type: "Event",
      generatedBy: authName,
      date,
      value: counts.events.length,
    },
    {
      name: "User Directory",
      type: "Users",
      generatedBy: authName,
      date,
      value: counts.usersCount,
    },
    {
      name: "Attendance Log",
      type: "Attendance",
      generatedBy: authName,
      date,
      value: counts.attendanceCount,
    },
    {
      name: "Feedback Digest",
      type: "Feedback",
      generatedBy: authName,
      date,
      value: counts.feedbackCount,
    },
    {
      name: "Certificates Issued",
      type: "Certificate",
      generatedBy: authName,
      date,
      value: counts.certCount,
    },
  ];
  const header = "Name,Type,Generated By,Date,Value";
  const lines = rows.map(
    (row) =>
      `"${row.name}","${row.type}","${row.generatedBy}","${row.date}","${row.value ?? ""}"`,
  );
  const extra = [
    "",
    "Recent Events",
    "Title,Status,Organizer,Updated",
    ...counts.events.slice(0, 30).map(
      (event) =>
        `"${String(event.title || "").replace(/"/g, '""')}","${event.status}","${String(event.organizerName || event.organizerEmail || "").replace(/"/g, '""')}","${event.updatedAt || ""}"`,
    ),
  ];
  return { csv: [header, ...lines, ...extra].join("\n"), rows };
}

/** List stored admin reports and optionally export CSV snapshots into categories. */
export async function GET(request: Request) {
  const auth = await requireAdminAuth(request);
  if ("error" in auth) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }

  try {
    const db = await getUserDb();
    const { searchParams } = new URL(request.url);
    const category = parseCategory(searchParams.get("category"));
    const format = searchParams.get("format");

    if (format === "csv") {
      const live = await loadLiveCounts(db);
      const { csv } = buildCsv(auth.session.name, live);
      const usersCsv = await buildUsersCsv(db);
      const csvBase64 = Buffer.from(csv, "utf8").toString("base64");
      const usersCsvBase64 = Buffer.from(usersCsv, "utf8").toString("base64");
      await storeCategorySnapshots({
        generatedBy: auth.session.name,
        generatedByEmail: auth.session.email,
        counts: {
          events: live.events.length,
          attendance: live.attendanceCount,
          feedback: live.feedbackCount,
          certificates: live.certCount,
          users: live.usersCount,
        },
        csvBase64,
        usersCsvBase64,
        db,
      });
      return new NextResponse(csv, {
        status: 200,
        headers: {
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="dc-space-report-${new Date().toISOString().slice(0, 10)}.csv"`,
        },
      });
    }

    const stored = await listAdminReports({
      category: category || undefined,
      limit: 50,
      db,
      syncEventPdfs: category === "event" || !category,
    });
    const stats = await getAdminReportStats(db);

    if (category) {
      return NextResponse.json({
        category,
        categoryLabel: CATEGORY_LABELS[category],
        reports: stored,
      });
    }

    const latestByCategory = new Map<string, (typeof stored)[number]>();
    for (const report of stored) {
      if (!latestByCategory.has(report.category)) {
        latestByCategory.set(report.category, report);
      }
    }

    const hubReports = ["event", "attendance", "feedback", "certificate", "users"]
      .map((key) => {
        const report = latestByCategory.get(key);
        if (report) {
          return {
            id: report.id,
            name: report.name,
            type: CATEGORY_LABELS[report.category as AdminReportCategory],
            generatedBy: report.generatedBy,
            date: report.date,
            format: report.format,
            value: report.recordCount,
            category: report.category,
            downloadPath: report.downloadPath || `/api/admin/reports/${report.id}/download`,
          };
        }
        return null;
      })
      .filter(Boolean);

    const recentReports =
      hubReports.length > 0
        ? hubReports
        : stored.slice(0, 5).map((report) => ({
            id: report.id,
            name: report.name,
            type: CATEGORY_LABELS[report.category],
            generatedBy: report.generatedBy,
            date: report.date,
            format: report.format,
            value: report.recordCount,
            category: report.category,
            downloadPath: report.downloadPath || `/api/admin/reports/${report.id}/download`,
          }));

    const live = await loadLiveCounts(db);

    return NextResponse.json({
      stats,
      reports: recentReports,
      categoryReports: stored,
      recentEvents: live.events.slice(0, 10).map((event) => ({
        title: event.title,
        status: event.status,
        organizer: event.organizerName || event.organizerEmail || "",
        updatedAt: event.updatedAt,
      })),
    });
  } catch (error) {
    const details = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { error: "Failed to load reports.", details },
      { status: 500 },
    );
  }
}
