import { NextResponse } from "next/server";
import { requireAdminAuth } from "@/lib/admin-server/require-admin-auth";
import { activitiesCollection } from "@/lib/user-server/activity";
import { getUserDb } from "@/lib/user-server/get-user-db";
import { eventsCollection } from "@/lib/events/types";

/** Build report rows from live user/event/activity data for admin Reports UI. */
export async function GET(request: Request) {
  const auth = await requireAdminAuth(request);
  if ("error" in auth) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }

  try {
    const db = await getUserDb();
    const [events, activities, usersCount, attendanceCount, feedbackCount, certCount] =
      await Promise.all([
        eventsCollection(db).find({}).sort({ updatedAt: -1 }).limit(50).toArray(),
        activitiesCollection(db).find({}).sort({ createdAt: -1 }).limit(50).toArray(),
        db.collection("users").countDocuments({
          role: { $nin: ["admin", "super-admin"] },
        }),
        db.collection("attendance_records").countDocuments({}),
        db.collection("feedback_entries").countDocuments({}),
        db.collection("certificates").countDocuments({}),
      ]);

    const monthStart = new Date();
    monthStart.setDate(1);
    monthStart.setHours(0, 0, 0, 0);
    const monthIso = monthStart.toISOString();

    const reports = [
      {
        name: "Events Summary",
        type: "Event",
        generatedBy: auth.session.name,
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        format: "Live",
        value: events.length,
      },
      {
        name: "User Directory",
        type: "Users",
        generatedBy: auth.session.name,
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        format: "Live",
        value: usersCount,
      },
      {
        name: "Attendance Log",
        type: "Attendance",
        generatedBy: auth.session.name,
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        format: "Live",
        value: attendanceCount,
      },
      {
        name: "Feedback Digest",
        type: "Feedback",
        generatedBy: auth.session.name,
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        format: "Live",
        value: feedbackCount,
      },
      {
        name: "Certificates Issued",
        type: "Certificate",
        generatedBy: auth.session.name,
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        format: "Live",
        value: certCount,
      },
    ];

    const thisMonthActivities = activities.filter(
      (a) => String(a.createdAt || "") >= monthIso,
    ).length;

    const { searchParams } = new URL(request.url);
    if (searchParams.get("format") === "csv") {
      const header = "Name,Type,Generated By,Date,Value";
      const lines = reports.map(
        (row) =>
          `"${row.name}","${row.type}","${row.generatedBy}","${row.date}","${row.value ?? ""}"`,
      );
      const extra = [
        "",
        "Recent Events",
        "Title,Status,Organizer,Updated",
        ...events.slice(0, 30).map(
          (event) =>
            `"${String(event.title || "").replace(/"/g, '""')}","${event.status}","${String(event.organizerName || event.organizerEmail || "").replace(/"/g, '""')}","${event.updatedAt || ""}"`,
        ),
      ];
      const csv = [header, ...lines, ...extra].join("\n");
      return new NextResponse(csv, {
        status: 200,
        headers: {
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="dc-space-report-${new Date().toISOString().slice(0, 10)}.csv"`,
        },
      });
    }

    return NextResponse.json({
      stats: {
        totalReportsGenerated: reports.length,
        thisMonth: thisMonthActivities,
        lastGenerated: reports[0]?.date || "—",
        mostDownloaded: reports[0]?.name || "—",
      },
      reports,
      recentEvents: events.slice(0, 10).map((e) => ({
        title: e.title,
        status: e.status,
        organizer: e.organizerName || e.organizerEmail || "",
        updatedAt: e.updatedAt,
      })),
      recentActivities: activities.slice(0, 15),
    });
  } catch (error) {
    const details = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { error: "Failed to load reports.", details },
      { status: 500 },
    );
  }
}
